# Generated by Django 3.2.7 on 2021-10-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('public_holidays', models.FloatField(default=2, verbose_name='公休天数')),
            ],
            options={
                'verbose_name': '周报期号',
                'verbose_name_plural': '周报排期表',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='报告者')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.reportschedule', verbose_name='周报号')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报列表',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='代码')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='records.project', verbose_name='父项目')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目一览表',
            },
        ),
    ]
